import os
from dotenv import load_dotenv

load_dotenv()

MAINNET_API_URL = "https://api.hyperliquid.xyz"
TESTNET_API_URL = "https://api.hyperliquid-testnet.xyz"

TESTNET_PRIVATE_KEY = os.getenv("TESTNET_PRIVATE_KEY", "")

MONITORED_ASSETS = ["BTC", "ETH", "SOL", "DOGE", "XRP", "SUI", "AVAX", "LINK"]

SCAN_INTERVAL_SECONDS = 30
MAX_ADDRESSES_PER_SCAN = 200
SCANNER_WORKERS = 10

# Legacy cascade (kept for scanner compatibility)
CASCADE_PROXIMITY_PCT = 0.02
CASCADE_DENSITY_THRESHOLD = 1
CASCADE_CLUSTER_WIDTH_PCT = 0.005
CASCADE_SIGNAL_THRESHOLD = 55
CASCADE_HIGH_CONFIDENCE = 75

# --- Trend Follower (replaces Cascade as primary strategy) ---
TREND_ADX_PERIOD = 14
TREND_ADX_THRESHOLD = 25
TREND_ADX_EXIT = 20
TREND_EMA_FAST = 21
TREND_EMA_SLOW = 55
TREND_CANDLE_INTERVAL = "4h"
TREND_CANDLE_COUNT = 100
TREND_PULLBACK_ATR_MULT = 0.5
TREND_STOP_ATR_MULT = 2.0
TREND_TP_ATR_MULT = 4.0
TREND_TRAIL_ATR_MULT = 1.5

# --- Momentum (enhanced weighted scoring) ---
MOMENTUM_RSI_PERIOD = 8
MOMENTUM_RSI_BULL = 60
MOMENTUM_RSI_BEAR = 40
MOMENTUM_MACD_FAST = 14
MOMENTUM_MACD_SLOW = 23
MOMENTUM_MACD_SIGNAL = 9
MOMENTUM_EMA_FAST = 7
MOMENTUM_EMA_SLOW = 26
MOMENTUM_BB_PERIOD = 20
MOMENTUM_BB_STD = 2
MOMENTUM_VOTE_THRESHOLD = 60
MOMENTUM_ADX_GATE = 20
MOMENTUM_CANDLE_INTERVAL = "1h"
MOMENTUM_CANDLE_COUNT = 100
MOMENTUM_HTF_INTERVAL = "4h"
MOMENTUM_HTF_CANDLE_COUNT = 50

# --- Funding Sniper (research-calibrated thresholds) ---
FUNDING_THRESHOLD = 0.0003
FUNDING_HIGH_THRESHOLD = 0.0008
FUNDING_SETTLEMENT_WINDOW = 1800
FUNDING_PERSISTENCE_PERIODS = 2
FUNDING_NORMALIZATION_EXIT = 0.0001
FUNDING_POSITION_SIZE = 200

# --- Pairs Reversion (cointegration-based) ---
PAIRS_ZSCORE_ENTRY = 2.0
PAIRS_ZSCORE_EXIT = 0.0
PAIRS_ZSCORE_STOP = 3.5
PAIRS_LOOKBACK_HOURS = 48
PAIRS_CANDLE_COUNT = 72
PAIRS_CANDLE_INTERVAL = "1h"
PAIRS_MIN_CORRELATION = 0.70
PAIRS_POSITION_SIZE_PER_LEG = 50

# --- Volatility Breakout (squeeze-based) ---
BREAKOUT_ATR_MULT = 1.5
BREAKOUT_SQUEEZE_BARS = 3
BREAKOUT_VOLUME_MULT = 1.5
BREAKOUT_CANDLE_INTERVAL = "15m"
BREAKOUT_LOOKBACK_CANDLES = 40

# --- Risk (research-calibrated) ---
POSITION_SIZE_USD = 50
MAX_LEVERAGE = 5
SLIPPAGE_PCT = 0.01
TRAILING_STOP_PCT = 0.015
INITIAL_STOP_PCT = 0.020
TAKE_PROFIT_PCT = 0.035
MAX_CONCURRENT_POSITIONS = 5
MAX_DAILY_LOSS_USD = 100
MIN_ORDER_SIZE_BTC = 0.001
TRADE_COOLDOWN_DEFAULT = 300

# --- Regime Detection ---
REGIME_UPDATE_INTERVAL = 300
REGIME_ADX_TRENDING = 25
REGIME_ADX_RANGING = 20

STOP_LOSS_POLL_INTERVAL = 3
PRICE_POLL_INTERVAL = 5
STRATEGY_POLL_INTERVAL = 15

AI_ENABLED_DEFAULT = False
AI_MODEL_ID = "us.anthropic.claude-haiku-4-5-20251001-v1:0"
AI_MAX_TOKENS = 200
AWS_REGION = os.getenv("AWS_DEFAULT_REGION", "us-east-1")

DASHBOARD_REFRESH_RATE = 1
LOG_MAX_LINES = 100
