import os
from dotenv import load_dotenv

load_dotenv()

MAINNET_API_URL = "https://api.hyperliquid.xyz"
TESTNET_API_URL = "https://api.hyperliquid-testnet.xyz"

TESTNET_PRIVATE_KEY = os.getenv("TESTNET_PRIVATE_KEY", "")

MONITORED_ASSETS = ["BTC", "ETH", "SOL", "DOGE", "XRP", "SUI", "AVAX", "LINK"]

SCAN_INTERVAL_SECONDS = 30
MAX_ADDRESSES_PER_SCAN = 200
SCANNER_WORKERS = 10

CASCADE_PROXIMITY_PCT = 0.02
CASCADE_DENSITY_THRESHOLD = 1
CASCADE_CLUSTER_WIDTH_PCT = 0.005
CASCADE_SIGNAL_THRESHOLD = 55
CASCADE_HIGH_CONFIDENCE = 75

MOMENTUM_RSI_PERIOD = 8
MOMENTUM_MACD_FAST = 14
MOMENTUM_MACD_SLOW = 23
MOMENTUM_MACD_SIGNAL = 9
MOMENTUM_EMA_FAST = 7
MOMENTUM_EMA_SLOW = 26
MOMENTUM_BB_PERIOD = 20
MOMENTUM_BB_STD = 2
MOMENTUM_VOTE_THRESHOLD = 4
MOMENTUM_CANDLE_INTERVAL = "1h"
MOMENTUM_CANDLE_COUNT = 100

POSITION_SIZE_USD = 50
MAX_LEVERAGE = 5
SLIPPAGE_PCT = 0.01
TRAILING_STOP_PCT = 0.008
INITIAL_STOP_PCT = 0.012
TAKE_PROFIT_PCT = 0.025
MAX_CONCURRENT_POSITIONS = 2
MAX_DAILY_LOSS_USD = 100
MIN_ORDER_SIZE_BTC = 0.001

STOP_LOSS_POLL_INTERVAL = 2
PRICE_POLL_INTERVAL = 3

AI_ENABLED_DEFAULT = False
AI_MODEL_ID = "us.anthropic.claude-haiku-4-5-20251001-v1:0"
AI_MAX_TOKENS = 200
AWS_REGION = os.getenv("AWS_DEFAULT_REGION", "us-east-1")

DASHBOARD_REFRESH_RATE = 1
LOG_MAX_LINES = 100
